class Gate:
    def target(self) -> int: ...
    def control(self) -> int: ...
    def gate_id(self) -> str: ...
    def sparse_matrix(self) -> SparseMatrix: ...
    def adjoint(self) -> Gate: ...
    def str(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

def gate(gate_id: str, target: int) -> Gate: 
    '''Create a one-qubit gate without parameter.
    gate_id can be "X", "Y", "Z", '''
    ...

class Circuit:
    def __init__(self) -> None:
        '''Instantiate an empty Circuit'''
        ...
    def add_gate(self, gate: Gate) -> None:
        '''add a Gate'''
        ...
    def add_circuit(self, circ: Circuit) -> None:
        '''add a Circuit'''
        ...
    def gates(self) -> str:
        '''Return a list of Gates
        in this Circuit'''
        ...
    def sparse_matrix(self) -> SparseMatrix:
        '''Return a SparseMatrix representing this circuit'''
        ...
    def size(self) -> int:
        '''Return the number of gates in this circuit'''
        ...
    def adjoint(self) -> Circuit:
        '''Return the adjoint of this circuit'''
        ...
    def canonicalize_pauli_circuit(self) -> complex:
        '''For a pauli circuit, order gates from smallest to largest target index,
        and combine gates with the same target. Return the complex prefactor resulting
        from the combination.'''
        ...
    def set_parameters(self, params: list) -> None:
        '''Reset the parameters of all Rz gates in the circuit,
        based on a list of real numbers.'''
        ...
    def get_num_cnots(self) -> int:
        '''Return the number of CX gates in the circuit'''
        ...
    def str(self) -> str:
        '''Return a string representation of the circuit'''
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
        
class SparseMatrix:
    def __init__(self) -> None: ...
